name: simple_player_flutter
description: "Simple Player - A dark-themed media player"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fvp: ^0.36.2
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  window_manager: ^0.5.1
  shared_preferences: ^2.5.5
  desktop_drop: ^0.7.1
  logger: ^2.5.0
  dynamic_color: ^1.8.1
  widgets_easier: ^0.0.10
  flutter_easy_animations: ^0.0.2
  ffi: ^2.1.4
  path: ^1.9.1
  crypto: ^3.0.6
  rust_lib_simple_player_flutter:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  video_texture_plugin:
    path: plugins/video_texture_plugin
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  freezed: ^3.2.5
  build_runner: ^2.15.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansSC-SemiBold.ttf
          weight: 600
