name: simple_player_flutter
description: "Simple Player - A dark-themed media player"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fvp: ^0.36.2
  path_provider: ^2.1.5
  file_picker: ^11.0.2
  window_manager: ^0.5.1
  shared_preferences: ^2.5.5
  desktop_drop: ^0.7.1
  logger: ^2.5.0
  dynamic_color: ^1.8.1
  widgets_easier: ^0.0.10
  flutter_easy_animations: ^0.0.2
  ffi: ^2.1.4
  path: ^1.9.1
  win32: ^5.12.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansSC-SemiBold.ttf
          weight: 600
