// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/events.dart';
import 'api/player.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 77711258;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_simple_player_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<double> crateApiPlayerMpvPlayerGetDuration({required MpvPlayer that});

  Future<bool> crateApiPlayerMpvPlayerGetIsPaused({required MpvPlayer that});

  Future<double> crateApiPlayerMpvPlayerGetPosition({required MpvPlayer that});

  Future<void> crateApiPlayerMpvPlayerLoadFile({
    required MpvPlayer that,
    required String path,
  });

  Future<MpvPlayer> crateApiPlayerMpvPlayerNew();

  Future<void> crateApiPlayerMpvPlayerPause({required MpvPlayer that});

  Future<void> crateApiPlayerMpvPlayerPlay({required MpvPlayer that});

  Future<void> crateApiPlayerMpvPlayerSeek({
    required MpvPlayer that,
    required PlatformInt64 positionMs,
  });

  Future<void> crateApiPlayerMpvPlayerSetMute({
    required MpvPlayer that,
    required bool muted,
  });

  Future<void> crateApiPlayerMpvPlayerSetSpeed({
    required MpvPlayer that,
    required double speed,
  });

  Future<void> crateApiPlayerMpvPlayerSetVolume({
    required MpvPlayer that,
    required double vol,
  });

  Future<void> crateApiPlayerMpvPlayerStop({required MpvPlayer that});

  Future<void> crateApiPlayerMpvPlayerTogglePause({required MpvPlayer that});

  Future<Stream<PlayerEvent>> crateApiEventsStartEventLoop();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<double> crateApiPlayerMpvPlayerGetDuration({required MpvPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerGetDurationConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerGetDurationConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_get_duration",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiPlayerMpvPlayerGetIsPaused({required MpvPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerGetIsPausedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerGetIsPausedConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_get_is_paused",
        argNames: ["that"],
      );

  @override
  Future<double> crateApiPlayerMpvPlayerGetPosition({required MpvPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerGetPositionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerGetPositionConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_get_position",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiPlayerMpvPlayerLoadFile({
    required MpvPlayer that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerLoadFileConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerLoadFileConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_load_file",
        argNames: ["that", "path"],
      );

  @override
  Future<MpvPlayer> crateApiPlayerMpvPlayerNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mpv_player,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerNewConstMeta =>
      const TaskConstMeta(debugName: "mpv_player_new", argNames: []);

  @override
  Future<void> crateApiPlayerMpvPlayerPause({required MpvPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerPauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "mpv_player_pause", argNames: ["that"]);

  @override
  Future<void> crateApiPlayerMpvPlayerPlay({required MpvPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerPlayConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerPlayConstMeta =>
      const TaskConstMeta(debugName: "mpv_player_play", argNames: ["that"]);

  @override
  Future<void> crateApiPlayerMpvPlayerSeek({
    required MpvPlayer that,
    required PlatformInt64 positionMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          sse_encode_i_64(positionMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerSeekConstMeta,
        argValues: [that, positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerSeekConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_seek",
        argNames: ["that", "positionMs"],
      );

  @override
  Future<void> crateApiPlayerMpvPlayerSetMute({
    required MpvPlayer that,
    required bool muted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          sse_encode_bool(muted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerSetMuteConstMeta,
        argValues: [that, muted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerSetMuteConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_set_mute",
        argNames: ["that", "muted"],
      );

  @override
  Future<void> crateApiPlayerMpvPlayerSetSpeed({
    required MpvPlayer that,
    required double speed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          sse_encode_f_64(speed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerSetSpeedConstMeta,
        argValues: [that, speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerSetSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_set_speed",
        argNames: ["that", "speed"],
      );

  @override
  Future<void> crateApiPlayerMpvPlayerSetVolume({
    required MpvPlayer that,
    required double vol,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          sse_encode_f_64(vol, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerSetVolumeConstMeta,
        argValues: [that, vol],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerSetVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_set_volume",
        argNames: ["that", "vol"],
      );

  @override
  Future<void> crateApiPlayerMpvPlayerStop({required MpvPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "mpv_player_stop", argNames: ["that"]);

  @override
  Future<void> crateApiPlayerMpvPlayerTogglePause({required MpvPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mpv_player(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerMpvPlayerTogglePauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerMpvPlayerTogglePauseConstMeta =>
      const TaskConstMeta(
        debugName: "mpv_player_toggle_pause",
        argNames: ["that"],
      );

  @override
  Future<Stream<PlayerEvent>> crateApiEventsStartEventLoop() async {
    final sink = RustStreamSink<PlayerEvent>();
    await handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_player_event_Sse(sink, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEventsStartEventLoopConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEventsStartEventLoopConstMeta =>
      const TaskConstMeta(debugName: "start_event_loop", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<PlayerEvent> dco_decode_StreamSink_player_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MpvPlayer dco_decode_box_autoadd_mpv_player(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mpv_player(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MpvPlayer dco_decode_mpv_player(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.isNotEmpty)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return MpvPlayer();
  }

  @protected
  PlayerEvent dco_decode_player_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PlayerEvent_Position(ms: dco_decode_f_64(raw[1]));
      case 1:
        return PlayerEvent_Duration(ms: dco_decode_f_64(raw[1]));
      case 2:
        return PlayerEvent_Paused(paused: dco_decode_bool(raw[1]));
      case 3:
        return PlayerEvent_State(state: dco_decode_String(raw[1]));
      case 4:
        return PlayerEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<PlayerEvent> sse_decode_StreamSink_player_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MpvPlayer sse_decode_box_autoadd_mpv_player(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mpv_player(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MpvPlayer sse_decode_mpv_player(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MpvPlayer();
  }

  @protected
  PlayerEvent sse_decode_player_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_ms = sse_decode_f_64(deserializer);
        return PlayerEvent_Position(ms: var_ms);
      case 1:
        var var_ms = sse_decode_f_64(deserializer);
        return PlayerEvent_Duration(ms: var_ms);
      case 2:
        var var_paused = sse_decode_bool(deserializer);
        return PlayerEvent_Paused(paused: var_paused);
      case 3:
        var var_state = sse_decode_String(deserializer);
        return PlayerEvent_State(state: var_state);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return PlayerEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_player_event_Sse(
    RustStreamSink<PlayerEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mpv_player(
    MpvPlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mpv_player(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mpv_player(MpvPlayer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_player_event(PlayerEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PlayerEvent_Position(ms: final ms):
        sse_encode_i_32(0, serializer);
        sse_encode_f_64(ms, serializer);
      case PlayerEvent_Duration(ms: final ms):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(ms, serializer);
      case PlayerEvent_Paused(paused: final paused):
        sse_encode_i_32(2, serializer);
        sse_encode_bool(paused, serializer);
      case PlayerEvent_State(state: final state):
        sse_encode_i_32(3, serializer);
        sse_encode_String(state, serializer);
      case PlayerEvent_Error(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
