// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

/// Start streaming mpv events to Dart.
///
/// Observes time-pos, duration, pause. Returns Stream<PlayerEvent>.
Future<Stream<PlayerEvent>> startEventLoop() =>
    RustLib.instance.api.crateApiEventsStartEventLoop();

@freezed
sealed class PlayerEvent with _$PlayerEvent {
  const PlayerEvent._();

  const factory PlayerEvent.position({required double ms}) =
      PlayerEvent_Position;
  const factory PlayerEvent.duration({required double ms}) =
      PlayerEvent_Duration;
  const factory PlayerEvent.paused({required bool paused}) = PlayerEvent_Paused;
  const factory PlayerEvent.state({required String state}) = PlayerEvent_State;
  const factory PlayerEvent.error({required String message}) =
      PlayerEvent_Error;
}
