// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MpvPlayer>>
abstract class MpvPlayer implements RustOpaqueInterface {
  Future<double> getDuration();

  Future<bool> getIsPaused();

  Future<double> getPosition();

  Future<void> loadFile({required String path});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MpvPlayer> newInstance() =>
      RustLib.instance.api.crateApiPlayerMpvPlayerNew();

  Future<void> pause();

  Future<void> play();

  Future<void> seek({required PlatformInt64 positionMs});

  Future<void> setMute({required bool muted});

  Future<void> setSpeed({required double speed});

  Future<void> setVolume({required double vol});

  Future<void> stop();

  Future<void> togglePause();
}
